version: '3.9'

services:
  pg_db:
    image: postgres:16
    container_name: pg_db
    environment:
      POSTGRES_DB: userapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  migrate:
    image: migrate/migrate
    depends_on:
      - pg_db
    volumes:
      - ./db/migration:/migrations
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      sleep 5 &&
      migrate -path=/migrations -database 'postgres://postgres:1234@pg_db:5432/userapi?sslmode=disable' up
      "
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - pg_db
    ports:
      - "8080:8080"
    environment:
      HOST: pg_db
      PORT: 5432
      USER: postgres
      PASSWORD: 1234
      DBNAME: userapi
      SSLMODE: disable
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: